apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bridge-ui.fullname" . }}
  labels:
    {{- include "bridge-ui.labels" . | nindent 4 }}
data:
  TARA_CONNECTOR_ADDRESS: {{ .Values.app.taraConnectorAddress | quote }}
  ETH_CONNECTOR_ADDRESS: {{ .Values.app.ethConnectorAddress | quote }}
  TARA_ERC20_LOCKING_CONNECTOR_ADDRESS: {{ .Values.app.taraErc20LockingConnectorAddress | quote }}
  ETH_ERC20_LOCKING_CONNECTOR_ADDRESS: {{ .Values.app.ethErc20LockingConnectorAddress | quote }}
  TARA_ERC20_MINTING_CONNECTOR_ADDRESS: {{ .Values.app.taraErc20MintingConnectorAddress | quote }}
  ETH_ERC20_MINTING_CONNECTOR_ADDRESS: {{ .Values.app.ethErc20MintingConnectorAddress | quote }}
  ETH_BRIDGE_ADDRESS: {{ .Values.app.ethBridgeAddress | quote }}
  TARA_BRIDGE_ADDRESS: {{ .Values.app.taraBridgeAddress | quote }}
  WTARA_TOKEN_ADDRESS: {{ .Values.app.wtaraTokenAddress | quote }}
  WETH_TOKEN_ADDRESS: {{ .Values.app.wethTokenAddress | quote }}